Repository iotaledger/iri, pull requests merged in 2018-11, with the labels that each got.

#1121 add "numberOfStaleTransactions" to getNeighbors API call
  src/main/java/com/iota/iri/network/Neighbor.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/service/dto/GetNeighborsResponse.java
Labels: C-API

#1103 add 'coordinatorAddress' to 'getNodeInfo' response.
  python-regression/tests/features/machine1/1_api_tests.feature
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
Labels: C-API

#1136 change `hash` package name to `crypto`
  src/main/java/com/iota/iri/BundleValidator.java
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/MilestoneTracker.java
  src/main/java/com/iota/iri/SignedFiles.java
  src/main/java/com/iota/iri/TransactionValidator.java
  src/main/java/com/iota/iri/crypto/Curl.java
  src/main/java/com/iota/iri/crypto/ISS.java
  src/main/java/com/iota/iri/crypto/ISSInPlace.java
  src/main/java/com/iota/iri/crypto/Kerl.java
  src/main/java/com/iota/iri/crypto/PearlDiver.java
  src/main/java/com/iota/iri/crypto/Sponge.java
  src/main/java/com/iota/iri/crypto/SpongeFactory.java
  src/main/java/com/iota/iri/model/AbstractHash.java
  src/main/java/com/iota/iri/model/Hash.java
  src/main/java/com/iota/iri/model/HashPrefix.java
  src/main/java/com/iota/iri/model/TransactionHash.java
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/UDPReceiver.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/utils/MapIdentityManager.java
  src/test/java/com/iota/iri/BundleValidatorTest.java
  src/test/java/com/iota/iri/MilestoneTrackerTest.java
  src/test/java/com/iota/iri/TransactionTestUtils.java
  src/test/java/com/iota/iri/TransactionValidatorTest.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/crypto/CurlTest.java
  src/test/java/com/iota/iri/crypto/ISSTest.java
  src/test/java/com/iota/iri/crypto/KerlTest.java
  src/test/java/com/iota/iri/crypto/PearlDiverTest.java
  src/test/java/com/iota/iri/model/HashTest.java
  src/test/java/com/iota/iri/service/APIIntegrationTests.java
  src/test/java/com/iota/iri/service/NodeIntegrationTests.java
  src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImplTest.java
  src/test/java/com/iota/iri/storage/TangleTest.java
Labels: E-Refactor

#1139 Document crypto package
  src/main/java/com/iota/iri/crypto/Curl.java
  src/main/java/com/iota/iri/crypto/ISS.java
  src/main/java/com/iota/iri/crypto/ISSInPlace.java
  src/main/java/com/iota/iri/crypto/Kerl.java
  src/main/java/com/iota/iri/crypto/PearlDiver.java
  src/main/java/com/iota/iri/crypto/Sponge.java
  src/main/java/com/iota/iri/crypto/SpongeFactory.java
Labels: C-Cryptography, E-Documentation, E-Refactor

#1141 Document zmq-messageQ
  src/main/java/com/iota/iri/zmq/MessageQ.java
  src/main/java/com/iota/iri/zmq/README.md
Labels: C-Docs

#1125 Document Bundle Validator
  src/main/java/com/iota/iri/BundleValidator.java
Labels: C-Consensus, E-Documentation

#1142 Transaction Validator Documentation
  src/main/java/com/iota/iri/TransactionValidator.java
Labels: C-Docs

#1140 Added javadoc to API
  src/main/java/com/iota/iri/service/API.java
Labels: C-API, C-Docs

#1143 Document dto
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/dto/AbstractResponse.java
  src/main/java/com/iota/iri/service/dto/AccessLimitedResponse.java
  src/main/java/com/iota/iri/service/dto/AddedNeighborsResponse.java
  src/main/java/com/iota/iri/service/dto/AttachToTangleResponse.java
  src/main/java/com/iota/iri/service/dto/CheckConsistency.java
  src/main/java/com/iota/iri/service/dto/ErrorResponse.java
  src/main/java/com/iota/iri/service/dto/ExceptionResponse.java
  src/main/java/com/iota/iri/service/dto/FindTransactionsResponse.java
  src/main/java/com/iota/iri/service/dto/GetBalancesResponse.java
  src/main/java/com/iota/iri/service/dto/GetInclusionStatesResponse.java
  src/main/java/com/iota/iri/service/dto/GetNeighborsResponse.java
  src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
  src/main/java/com/iota/iri/service/dto/GetTipsResponse.java
  src/main/java/com/iota/iri/service/dto/GetTransactionsToApproveResponse.java
  src/main/java/com/iota/iri/service/dto/GetTrytesResponse.java
  src/main/java/com/iota/iri/service/dto/IXIResponse.java
  src/main/java/com/iota/iri/service/dto/RemoveNeighborsResponse.java
  src/main/java/com/iota/iri/service/dto/WereAddressesSpentFrom.java
Labels: C-Docs

#1161 tweak tip selection documentation.
  src/main/java/com/iota/iri/service/tipselection/EntryPointSelector.java
  src/main/java/com/iota/iri/service/tipselection/RatingCalculator.java
  src/main/java/com/iota/iri/service/tipselection/TailFinder.java
  src/main/java/com/iota/iri/service/tipselection/TipSelector.java
  src/main/java/com/iota/iri/service/tipselection/WalkValidator.java
  src/main/java/com/iota/iri/service/tipselection/Walker.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumulativeWeightCalculator.java
  src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImpl.java
  src/main/java/com/iota/iri/service/tipselection/impl/RatingOne.java
  src/main/java/com/iota/iri/service/tipselection/impl/TailFinderImpl.java
  src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java
  src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java
  src/main/java/com/iota/iri/service/tipselection/impl/WalkerAlpha.java
Labels: C-Docs, C-Tip Selection, E-Documentation
