Repository iotaledger/iri, pull requests merged in 2018-08, with the labels that each got.

#903 Remove WalkValidator cache of tips that are below max depth
  src/main/java/com/iota/iri/IRI.java
  src/main/java/com/iota/iri/Iota.java
  src/main/java/com/iota/iri/conf/Configuration.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java
  src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java
  src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
Labels: C-Consensus

#909 Fix minor issues with issue template
  .github/issue_template.md
Labels: E-Meta

#908 remove checkSolidity mocks
  src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
Labels: C-Validation

#913 some TransactionValidator fixes regarding solidity
  src/main/java/com/iota/iri/TransactionValidator.java
  src/main/java/com/iota/iri/controllers/TipsViewModel.java
  src/main/java/com/iota/iri/service/TipsSolidifier.java
Labels: C-Validation

#947 Contributing guidelines
  CONTRIBUTING.md
  README.md
Labels: E-Meta
