Repository iotaledger/iri, pull requests merged in 2019-03, with the labels that each got.

#1100 Introducing a Cuckoo Filter for local snapshots
  src/main/java/com/iota/iri/utils/BitSetUtils.java
  src/main/java/com/iota/iri/utils/datastructure/CuckooFilter.java
  src/main/java/com/iota/iri/utils/datastructure/impl/CuckooFilterImpl.java
  src/test/java/com/iota/iri/utils/datastructure/impl/CuckooFilterImplTest.java
Labels: C-Local Snapshots, L-Groom

#1326 Use xxHash instead of SHA-256 on incoming transaction hashes cache
  pom.xml
  src/main/java/com/iota/iri/network/Node.java
Labels: C-Network, E-Performance

#1347 Fix: log inconsistent addresses in debug mode
  src/main/java/com/iota/iri/service/snapshot/impl/SnapshotStateImpl.java
Labels: C-Logging
