Repository iotaledger/iri, pull requests merged in 2019-08, with the labels that each got.

#1562 Update dependencies
  pom.xml
Labels: C-API, C-Configuration

#1157 Document Persistence Provider
  src/main/java/com/iota/iri/storage/PersistenceProvider.java
  src/main/java/com/iota/iri/storage/Tangle.java
Labels: C-DB, C-Docs, E-Documentation

#1573 Use maven assembly plugin to create one jar with all dependencies
  pom.xml
Labels: C-Build

#1330 Change: Curl improvement
  src/main/java/com/iota/iri/crypto/Curl.java
  src/main/java/com/iota/iri/crypto/PearlDiver.java
Labels: C-Cryptography

#1169 Document Persistable and Indexable
  src/main/java/com/iota/iri/storage/Indexable.java
  src/main/java/com/iota/iri/storage/Persistable.java
Labels: C-DB, C-Docs, E-Documentation
