Repository iotaledger/iri, pull requests merged in 2020-03, with the labels that each got.

#1763 Fix: made gb default lowercase
  src/main/java/com/iota/iri/utils/IotaUtils.java
  src/test/java/com/iota/iri/utils/IotaUtilsTest.java
Labels: C-Configuration, C-Pruning

#1759 Documentation: Description for milestone start index
  src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
Labels: C-API

#1782 Fix: typo
  README.md
Labels: C-Docs

#1764 Update regression structure
  python-regression/README.md
  python-regression/tests/features/machine1/1_local_snapshots_tests.feature
  python-regression/tests/features/machine1/config.yml
  python-regression/tests/features/machine1/output.yml
  python-regression/tests/features/machine2/2_blowball_tests.feature
  python-regression/tests/features/machine2/config.yml
  python-regression/tests/features/machine2/output.yml
  python-regression/tests/features/machine3/3_transaction_tests.feature
  python-regression/tests/features/machine3/config.yml
  python-regression/tests/features/machine3/output.yml
  python-regression/tests/features/machine4/4_api_tests.feature
  python-regression/tests/features/machine4/config.yml
  python-regression/tests/features/machine4/output.yml
  python-regression/tests/features/machine5/5_stitching.feature
  python-regression/tests/features/machine5/config.yml
  python-regression/tests/features/machine5/output.yml
  python-regression/tests/features/machine6/6_milestone_validation.feature
  python-regression/tests/features/machine6/__init__.py
  python-regression/tests/features/machine6/config.yml
  python-regression/tests/features/machine6/output.yml
  python-regression/tests/features/steps/api_test_steps.py
Labels: C-RegressionTests

#1788 Delete get tips
  python-regression/tests/features/machine1/1_api_tests.feature
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/ApiCommand.java
  src/test/java/com/iota/iri/service/APIIntegrationTests.java
Labels: C-API

#1774 Only cache after exists check passes
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
Labels: C-Solidification, T-Bug

#1802 Check validity rules on tip-sel and check-consistency only
  src/main/java/com/iota/iri/BundleValidator.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/ledger/LedgerService.java
  src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java
  src/main/java/com/iota/iri/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesServiceImpl.java
  src/test/java/com/iota/iri/BundleValidatorTest.java
  src/test/java/com/iota/iri/TangleMockUtils.java
  src/test/java/com/iota/iri/TransactionTestUtils.java
  src/test/java/com/iota/iri/service/ledger/impl/LedgerServiceImplTest.java
Labels: C-Consensus
